on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@artbog/intercom'
          command: release-pr
          pull-request-title-pattern: 'chore${scope}: release${component} v${version}'
          pull-request-header: ''
          include-v-in-tag: true
